### ISSUE TITLE
Cannot find linaris-server

### ISSUE THREAD

**Issue by Elikill58** [jordanbonaldi/Linaris-Zombie#1]
I can download all other resources, but not this one

**Comment by jordanbonaldi** [comment]
C'est une ancienne version qui utilisait une autre api, je vais voir si j'ai pas la version lié à l'api 2017

**Comment by Elikill58** [comment]
merci :)

**Comment by jordanbonaldi** [comment]
Je viens de mettre à jour avec la nouvelle api:
Il te faut la GameAPI: https://github.com/jordanbonaldi/Linaris-GameAPI
Il te faut l'API centrale: https://github.com/jordanbonaldi/Linaris-API
A savoir que le plugin peut fonctionner sans les deux APIs la, il suffit de supprimer le systeme de give au player (coins, kits..)

**Comment by Elikill58** [comment]
Merci ! Je viens de voir que tu es passé d'Eclipse à Intellij x)
Je check ça tout à l'heure
